### ISSUE TITLE
t&c/privacy/cookie policy

### ISSUE THREAD

**Issue by peteaylward** [refreshoxford/refreshoxford.co.uk#4]
footer links need adding back in and content finding for those pages. perhaps from previous refresh oxford site?

**Comment by pandalion** [comment]
None of this info on previous refresh oxford site... @ghickman any idea where this content might come from?

**Comment by ghickman** [comment]
Let's sack the cookie policy off, it's silly.

We were going to use the equality write up from PyCon (it's CC) which is on their site (that's PyCon US).

As for t&cs/privary, not entirely sure we need those? @jturnbull thoughts?

**Comment by jturnbull** [comment]
Just use the Ts&Cs from the Incuna site

**Comment by pandalion** [comment]
@ghickman @jturnbull t&cs and code of conduct are added (sorry keep forgetting to link commit to issue), you may want to change the copy a bit.
